import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider, Viewport } from "@radix-ui/react-toast";
import { type AppType } from "next/app";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ClerkProvider {...pageProps}>
      <Head>
        <title>Chirpatorio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastProvider duration={3000}>
        <Component {...pageProps} />
        <Viewport className="fixed bottom-0 right-0 w-full p-4" />
      </ToastProvider>
    </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
