import { useUser } from "@clerk/nextjs";
import {
  CreatePostWizard,
  LoadingSpinner,
  Navigation,
  Post,
} from "~/components";
import { api } from "~/utils/api";
import Head from "next/head";

export default function Home() {
  const { data, isLoading: isLoadingPosts } = api.posts.getAll.useQuery();
  const { isLoaded: isUserLoaded } = useUser();

  if (!data && !isLoadingPosts) return <div>No data</div>;

  return (
    <>
      <Head>
        <title>Chirpatorio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className="wrapper relative top-[74px]">
        <div className="flex flex-col gap-4 p-4">
          {isUserLoaded ? (
            <CreatePostWizard />
          ) : (
            <div className="grid">
              <LoadingSpinner className="place-self-center" />
            </div>
          )}
          {isLoadingPosts ? (
            <div className="grid">
              <LoadingSpinner className="place-self-center" />
            </div>
          ) : (
            <div>
              {data.map((post) => (
                <Post key={post.post.id} {...post} />
              ))}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
