import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { LoadingSpinner, Post, ProfileImage } from "~/components";
import { api } from "~/utils/api";
import Head from "next/head";

export default function ProfilePage() {
  const { data, isLoading: isLoadingPosts } = api.posts.getAll.useQuery();
  const { isSignedIn, isLoaded: isUserLoaded, user } = useUser();

  if (!data && !isLoadingPosts) return <div>No data</div>;
  if (!user) return <div>No user</div>;

  return (
    <>
      <Head>
        <title>Chirpatorio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="fixed left-0 right-0 top-0 flex h-[74px] items-center gap-4 p-4">
        {!isSignedIn && <SignInButton />}
        {isSignedIn && <SignOutButton />}
      </nav>
      <main className="wrapper relative top-[74px]">
        <div className="flex flex-col gap-4 p-4">
          <div className="grid grid-cols-[1fr,84px]">
            <h1 className="col-start-1 text-2xl font-bold">Jon Doe</h1>
            <p className="col-start-1 mb-4">jon.doe</p>
            <ProfileImage
              className="col-start-2 row-span-2 row-start-1 h-full w-full"
              src={user.imageUrl}
            />
          </div>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatem
            eveniet quos libero dignissimos possimus omnis impedit pariatur
            cumque placeat earum, voluptatum, sit deleniti dolor magnam mollitia
            obcaecati inventore voluptas excepturi?
          </p>

          <section className="flex flex-col gap-8">
            <h2 className="text-lg font-bold">Posts</h2>
            {isLoadingPosts ? (
              <div className="grid">
                <LoadingSpinner className="place-self-center" />
              </div>
            ) : (
              <div>
                {data.map((post) => (
                  <Post key={post.post.id} {...post} />
                ))}{" "}
              </div>
            )}
          </section>
        </div>
      </main>
    </>
  );
}
